### ISSUE TITLE
Create test cases using jest

### ISSUE THREAD

**Issue by ssbozy** [HendrixString/adobe-cep-react-create#11]
I am trying to write test cases and running into CSInterface scope issues. Did you try any of it?

**Comment by HendrixString** [comment]
hi @ssbozy ,

so the plugin has two area, right? the pure front-end side, which I believe
can be fully tested like any front end side.

the other side is the session side, which uses Node.js and native Adobe API,
this I believe can also be accomplished. 

I think that the strategy is divide between front-end and session sides also for testing

I may be wrong though, as I have never tried to perform unit tests with this project,
I haven't had enough time to explore it
