### ISSUE TITLE
Webpack Configuration Error? 

### ISSUE THREAD

**Issue by njho** [HendrixString/adobe-cep-react-create#18]
Hi, 

After `npm install`, I try `npm start` I receive the following error: 

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__
```

Is it possible that there is a webpack configuration errror? 

Best Regards

**Comment by HendrixString** [comment]
I remember this.
what Node version are you using ?
I think u need to upgrade

**Comment by njho** [comment]
I'll take a look at this. Thanks @HendrixString

**Comment by njho** [comment]
Confirmed. Working with `npm -v 6.13.7`
