### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by MrDogeBro** [HendrixString/adobe-cep-react-create#28]
### The Problem
When I am trying to run `npm run build:dev`, I get the following error:
```js
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'chalk'
```

My temporary fix was to do `npm install chalk`, which fixed that error. Now it would run but I am getting a new error.
```node
copying session node-modules...

Error: ENOENT: no such file or directory, link 
'/Users/aedan/Desktop/adobereact/src/session-src/node_modules'
-> '/Users/aedan/Desktop/adobereact/dist/com.hendrix.demo/node_modules'
```

If anyone can explain this that would be great. Thanks.

### Info
**OS**: *Mac OSX*
**Date of Git Clone**: *7/25/2020*

**Comment by HendrixString** [comment]
hi
it means you did not install the package.
you should have done
`npm install` after download

**Comment by MrDogeBro** [comment]
Ok. Thanks. You should write actual instructions for installing then and make sure everything on the README is clear so that it is easy for anyone to understand.
