### ISSUE TITLE
Build issue whith copying manifest.xml

### ISSUE THREAD

**Issue by 80prozent** [HendrixString/adobe-cep-react-create#3]
Hey

I tried this boilerplate, and i think its very nice.
Was looking for some info about react for adobe extensions, and found this which is very helpful.

I got a error when trying to build it, because the manifest.xml could not be copied.

The problem is in build-scripts.build.js

it tries to copy the file like this:

```
var xml_out_file = path.join(pluginFolder, 'CSXS', 'manifest.xml')
fs.writeFileSync(xml_out_file, rendered_xml, 'utf-8')
```

however if the folder structure doesnt exists, the opperation will error.

so to fix it i added this right before the file-copy:

```
var xml_out_dir = path.join(pluginFolder, 'CSXS')
fs.mkdir(xml_out_dir, { recursive: true }, (err) => {if (err) throw err;});
```

that seem to fix it, and i get it builded now.

Not tested the archieve command yet, but the result of the build (dist) works fine when i copy it to my extension-dir.

**Comment by HendrixString** [comment]
hi @80prozent ,
happy to hear that you found it useful !!!

please feel free to send a pull request with your fix
