### ISSUE TITLE
session-src/node-modules: no such file or directory

### ISSUE THREAD

**Issue by RolfCl** [HendrixString/adobe-cep-react-create#4]
I got an error on line 57 in build.js when running "npm run build:dev" (and prod):

line 57:
utils.copyRecursiveSync(fromSrc('session-src/node_modules'), fromPlugin('node_modules'))

error:
Error: ENOENT: no such file or directory, link '/folder/src/session-src/node_modules' -> '/folder/dist/com.hendrix.demo/node_modules'

What have I missed?

**Comment by HendrixString** [comment]
hi @RolfCl 

this is a known issue, simply create a 'node_modules` directory inside `session-src/`
