### ISSUE TITLE
How to debug session-src 

### ISSUE THREAD

**Issue by Loxe** [HendrixString/adobe-cep-react-create#42]
Hi ~ Tomer Shalev

First of all, this project is very awesome.

I just have a little question, How to debug session-src？

I saw "package.json" ,but that exclude "session-src" debug mode.

My first development with nodejs and webpack, So please~  thx :)

**Comment by HendrixString** [comment]
@Loxe I remember it is written in the readme file. you debug with chrome debugger (google chrome).
don't mind the package.json. The project has two sub projects. The main one is for frontend and bundeling, the
other is for session. You can only debug once you run it in debug mode within Adobe product. Then, you open google chrome and connect to a local host with port(mentioned in the readme)

**Comment by Loxe** [comment]
Thank you for your reply. Now I also use CEF client debug. Today, I've been thinking about whether there is a more convenient way... Unfortunately, I haven't found it yet

**Comment by Loxe** [comment]
Thank you for your reply. Now I also use CEF client debug. Today, I've been thinking about whether there is a more convenient way... Unfortunately, I haven't found it yet
