### ISSUE TITLE
Enabling hotloading

### ISSUE THREAD

**Issue by ssbozy** [HendrixString/adobe-cep-react-create#5]
Hi Tomer, 
Quick question: Is there a way to setup hotloading in the app to avoid npm run build after every code modification?

**Comment by HendrixString** [comment]
hi @ssbozy 

unfortunately no, BUT,
if the only thing you try to test is UI, then
you can just `npm start` and it will start the project in the browser
and then you will have updates everytime you make changes to the files,
you get it for free via webpack dev server.

I used this feature A LOT to setup my UI and iterate quickly

hope this helps

**Comment by ssbozy** [comment]
Hi @HendrixString Thansk for the quick tip. I am also trying to run some CSInterface commands along with the UI and testing both without having hotloading seems to be a pain.

**Comment by HendrixString** [comment]
I feel your pain in that matter
