### ISSUE TITLE
Running npm start shows an empty html

### ISSUE THREAD

**Issue by yahiaboudah** [HendrixString/adobe-cep-react-create#51]
How do I make the server template html show my app?

**Comment by HendrixString** [comment]
try `npm run client:dev-server`

**Comment by yahiaboudah** [comment]
That's the same as `npm start`, for some reason I'm getting this: _Entrypoint undefined = index.html_

**Comment by HendrixString** [comment]
Super weird, can you try cloning another project and run npm install and then start.
Which OS are you using ?

**Comment by HendrixString** [comment]
Also, root node modules are front-end web modules.
and, root of session-src is a separate modules for native node.js modules,
so keep that in mind

**Comment by yahiaboudah** [comment]
I've had to update a lot of deps, and eventually got it to work. I also replaced webpack with vite for faster builds. Thanks for opensourcing this! I learned a lot from it
