### ISSUE TITLE
How to setup this extension with tailwindcss ? 

### ISSUE THREAD

**Issue by Suraj-Gole** [HendrixString/adobe-cep-react-create#56]
I have to create cep extension with tailwindcss can you help me in it? Do you have any solution ?

**Comment by HendrixString** [comment]
You can add a build step in webpack for example for tailwind or include tailwind statically

**Comment by Suraj-Gole** [comment]
How to add a build step for tailwind? I have tried a lot but the tailwind CSS is not applying to components. Please provide an example by adding that build step in Webpack.

**Comment by HendrixString** [comment]
@Suraj-Gole tailwind has a config file, which you need to tell it where your components are.
Also, you can use the CDN without config:
[https://tailwindcss.com/docs/installation/play-cdn](https://tailwindcss.com/docs/installation/play-cdn)
