### ISSUE TITLE
Build  Error Manifest.xml

### ISSUE THREAD

**Issue by kostimarko** [HendrixString/adobe-cep-react-create#6]
After cloning the repo and running `npm run build:dev` I get the error

```/Users/sr1/Developer/MCLibCEP/adobe-cep-react-create/dist/com.MCPhotoLib.demo/CSXS/manifest.xml'```

**Comment by HendrixString** [comment]
hi @kostimarko 

what is the error exactly ?
maybe the CSXS folder is not created

**Comment by kostimarko** [comment]
whoops, sorry. You're correct. the CSXS folder doesn't get created

**Comment by HendrixString** [comment]
it is supposed to get generated, BUT
i heard some developers saying it wasn't for some reason

**Comment by kostimarko** [comment]
I'd love to use this to build some extensions. 

let me know how I can help debug

**Comment by HendrixString** [comment]
were you able to make it work ?

**Comment by kostimarko** [comment]
I will test in a few hours and report back.
