### ISSUE TITLE
How to add a build step for tailwind? I have tried a lot but the tailwind CSS is not applying to components. Please provide an example by adding that build step in Webpack.

### ISSUE THREAD

**Issue by Suraj-Gole** [HendrixString/adobe-cep-react-create#63]
How to add a build step for tailwind? I have tried a lot but the tailwind CSS is not applying to components. Please provide an example by adding that build step in Webpack.

_Originally posted by @Suraj-Gole in https://github.com/HendrixString/adobe-cep-react-create/issues/56#issuecomment-1704596487_

**Comment by HendrixString** [comment]
Hi @Suraj-Gole , I think you dont have to use the tailwind compiler, they also have a published css file, that you can use right away. I will look it up
