### ISSUE TITLE
mkdir -p fails in windows

### ISSUE THREAD

**Issue by MrDChristop** [HendrixString/adobe-cep-react-create#7]
You forgot to mention in the docs to do "npm install" 
Which fails in the end in Windows because mkdir -p does not run. In windows there is no -p and the path uses backslashes instead of forward slashes.
I fixes these by adding mkdirp in the dependencies package.json (npm install mkdirp --save)
  "dependencies": {
    "@material-ui/core": "^1.4.2",
    "@material-ui/icons": "^2.0.0",
    "console-feed": "^2.8.3",
    "mkdirp": "^0.5.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
}

and then this to the postinstall in package.json  
"postinstall": "mkdirp src/session-src/node_modules",

Without these changes the npm run build:dev etc commands failed

**Comment by HendrixString** [comment]
@MrDChristop thank you very much !!!
can you please make a pull request so Windows users will enjoy
your fixes as well ?
