### ISSUE TITLE
Deploy.js is not right

### ISSUE THREAD

**Issue by MrDChristop** [HendrixString/adobe-cep-react-create#8]
Hi the below does not make sense in deployDevMode
        execSync('defaults write com.adobe.CSXS.15 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.14 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.13 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.12 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.11 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.10 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.9 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.8 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.7 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.6 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.5 PlayerDebugMode 1', {stdio:[0,1,2]})
        execSync('defaults write com.adobe.CSXS.4 PlayerDebugMode 1', {stdio:[0,1,2]})

The CSXS goes as much as 9 (CC2019 has CEP 9).
And it does not seem to work on windows. Failing permissions. 
Do you test on Windows?
![image](https://user-images.githubusercontent.com/26302806/58633486-42259800-82f1-11e9-98e5-d2ae3db02745.png)

**Comment by MrDChristop** [comment]
I see that the current command is only for MA. Yeah Mac rulz but i need it for windows.
Until this is fixed i propose you skip this step for windows

**Comment by MrDChristop** [comment]
I did create a patch for that.
I created a windows batch command which queries the registry in windows and if the CSXS entry exists meaning the product is installed the debug flag is set.

The solution to the install path is that you can install the extension per user without priviledge problems.
C:\Users\<username>\AppData\Roaming\Adobe\<CEPVersion>\extensions\

```
function resolveExtensionFolder() {
    if (isWindows) {
        //return 'C:\\Program Files (x86)\\Common Files\\Adobe\\CEP\\extensions';
        return os.userInfo().homedir+"\\AppData\\Roaming\\Adobe\\CEP\\extensions\\";
    } else {
        return path.join(os.homedir(), 'Library/Application Support/Adobe/CEP/extensions')
    }
}
```

**Comment by HendrixString** [comment]
@MrDChristop 
hi, I dont have Windows, so I didn't had a chance.
Please, create a patch and a pull request with your fixes
so others can benefit as well :)

**Comment by Merkur39** [comment]
Hi, I have the same problem on Windows too
![Capture](https://user-images.githubusercontent.com/14182143/74738148-99401400-5256-11ea-99db-f5fb0f5b7d18.PNG)

I have fixed the following issues:

> Error: EPERM: operation not permitted, symlink ...

*Because some directories doesn't exist*

> Error: Command failed: defaults write com.adobe.CSXS.15 PlayerDebugMode 1

*This command does not exist on Windows*

I will create a PR soon :)

**Comment by HendrixString** [comment]
@Merkur39 thank you very much !!!
