### ISSUE TITLE
'webpack-dev-server' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by syedsameerali** [HendrixString/adobe-cep-react-create#9]
webpack-dev-server is not included as a dev dependency in package.json. As this can be easily solved by `npm i --save-dev webpack-dev-server`, I was wondering if  it has not been included for any reason? As it has been stated in the readme of the project as a feature of adobe-cep-react-create.

Quote from Readme
> a nice feature, that it has is that you can use webpack-dev-server to see your UI results with watching at the browser, simply use:
>npm start or
>npm run client:dev-server this will generate the template html for you and run it in your >browser, and will rebuild on code changes which is nice to have.

<details>
<summary>npm error log</summary

npm start

cep-test@1.0.0 start C:\Users\Pavilion\Desktop\adobe-cep-react-create-master
npm run client:dev-server

 cep-test@1.0.0 client:dev-server C:\Users\Pavilion\Desktop\adobe-cep-react-create-master
 webpack-dev-server --config ./build-scripts/webpack.client.config.js --env.target=web --mode development --open

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cep-test@1.0.0 client:dev-server: `webpack-dev-server --config ./build-scripts/webpack.client.config.js 
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cep-test@1.0.0 client:dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\_Bin\npm-cache\_logs\2019-07-10T14_46_02_989Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cep-test@1.0.0 start: `npm run client:dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cep-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\_Bin\npm-cache\_logs\2019-07-10T14_46_03_038Z-debug.log
</details>

Thank you for creating this awesome project. I was wondering why it has not gained more popularity as CEP development is definitely not straight forward and intuitive. I find this project using Webpack and react make working with CEP a whole lot more simpler and enjoyable.

With much thanks and appreciation,

**Comment by HendrixString** [comment]
hi @syedsameerali 

thank you for your kind words.
You are correct, it should be in the dev dependencies.
would you please offer a Pull Request with this change ?

all the best
Tomer

**Comment by HendrixString** [comment]
fixed at https://github.com/HendrixString/adobe-cep-react-create/pull/10
